import {StyleSheet} from 'react-native';
const researchStyle = StyleSheet.create({
  cardContainer: {
    width: 343,
    height: 389,
    marginHorizontal: 16,
    flexDirection: 'column',

    position: 'absolute',
    marginBottom: 385,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EEEAF3',
    elevation: 5,
    borderRadius: 5,
    alignSelf: 'center',
  },
  Title: {
    color: '#333',
    marginLeft: 16,
    marginTop: 13,
    marginRight: 248,
    width: 'auto',
    height: 22,
    fontFamily: 'Avenir Roman',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  cardTitle: {
    color: '#D2BAF5',
    paddingLeft: 15,
    paddingTop: 19,
    paddingRight: 219,
    paddingBottom: 70,

    fontFamily: 'Montserrat',

    position: 'absolute',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  cardStartingInText: {
    color: '#B296DC',
    paddingLeft: 178,
    paddingTop: 19,
    paddingRight: 98,
    paddingBottom: 70,
    fontFamily: 'Montserrat',
    position: 'absolute',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'right',
  },
  cardStartingIn: {
    color: '#B296DC',
    paddingLeft: 273,
    paddingTop: 19,
    paddingRight: 15,
    paddingBottom: 70,
    fontFamily: 'Montserrat',
    position: 'absolute',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  InfoIcon: {
    paddingLeft: 130,
    paddingTop: 20,
    paddingRight: 198,
    paddingBottom: 71,
    position: 'absolute',
  },
  clockIcon: {
    paddingTop: 20,
    paddingLeft: 251,
    paddingBottom: 70,
    paddingRight: 76,
    position: 'absolute',
  },
  bitcoinDescriptionContainer: {
    paddingLeft: 15,
    fontFamily: 'Montserrat',
    paddingTop: 50,
    paddingRight: 98,
    paddingBottom: 16,
    position: 'absolute',
  },
  amount: {
    color: '#FFF',
    // font-family: Montserrat;
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 19,
  },
  timing: {
    color: '#FFF',
    fontFamily: 'Montserrat',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
  },
  headerCardContainer: {
    borderTopLeftRadius: 4,
    width: 341,
    height: 104,
    borderTopRightRadius: 4,
  },
  prediction: {
    paddingTop: 125,
    paddingBottom: 224,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    top: -105,
  },
  descriptionHeader: {
    color: '#B5C0C8',
    textAlign: 'center',
    fontFamily: 'Montserrat',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',
    // line-height: noral,
  },
  descriptionContent: {
    color: '#333',
    textAlign: 'center',
    fontFamily: 'AvenirNext',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  predictionQuestion: {
    color: '#727682',
    fontFamily: 'Montserrat',
    fontSize: 14,
    paddingTop: 187,
    paddingLeft: 15,
    paddingRight: 153,
    paddingBottom: 185,
    fontStyle: 'normal',
    fontWeight: '600',
    position: 'absolute',
    // line-height: normal,
  },
  predictionButtonContainer: {
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    paddingTop: 218,
    paddingBottom: 131,
    paddingLeft: 16,
    // paddingRight:,
    alignItems: 'center',
  },
  predictionButton: {
    flexDirection: 'row',
    backgroundColor: 'black',
    borderRadius: 45,
    border: 1.7,
    justifyContent: 'center',
    alignItems: 'center',
    width: 147.5,
    height: 40,
  },
  predictionButtonText: {
    marginHorizontal: 4,
    color: '#FFF',
    fontFamily: 'Montserrat',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  bottomCardContainer: {
    marginTop: 278,
    marginLeft: 1,
    marginRight: 1,
    marginBottom: 1,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    position: 'absolute',
    width: 341,
    height: 110,
  },
  bottomCardTotalChart: {
    flexDirection: 'row',
    width: 101,
    alignItems: 'center',
  },
  bar: {
    flexDirection: 'row',
  },
  predictionStat: {
    color: '#B5C0C8',
    fontFamily: 'Montserrat',

    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',
    // line-height:'normal';
  },
});
export default researchStyle;
