import {StyleSheet} from 'react-native';
const researchStyle = StyleSheet.create({
  cardContainer: {
    width: 343,
    height: 389,
    marginHorizontal: 16,
    flexDirection: 'column',
    marginTop: 51,
    position: 'absolute',
    marginBottom: 385,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EEEAF3',
    elevation: 5,
    borderRadius: 5,
  },
  Title: {
    color: '#333',
    marginLeft: 16,
    marginTop: 13,
    width: 'auto',
    height: 22,
    marginRight: 248,
    marginBottom: 790,
    // font-family: Avenir Next,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  cardTitle: {
    color: '#D2BAF5',
    paddingLeft: 15,
    paddingTop: 19,
    paddingRight: 219,
    paddingBottom: 70,
    // font-family: Montserrat;
    position: 'absolute',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  cardStartingInText: {
    color: '#B296DC',
    paddingLeft: 178,
    paddingTop: 19,
    paddingRight: 98,
    paddingBottom: 70,
    // font-family: Montserrat;
    position: 'absolute',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',

    textAlign: 'right',
  },
  cardStartingIn: {
    color: '#B296DC',
    paddingLeft: 273,
    paddingTop: 19,
    paddingRight: 15,
    paddingBottom: 70,
    // font-family: Montserrat;
    position: 'absolute',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  InfoIcon: {
    paddingLeft: 130,
    paddingTop: 20,
    paddingRight: 198,
    paddingBottom: 71,
    position: 'absolute',
  },
  clockIcon: {
    paddingTop: 20,
    paddingLeft: 251,
    paddingBottom: 70,
    paddingRight: 76,
    position: 'absolute',
  },
  bitcoinDescriptionContainer: {
    paddingLeft: 15,

    paddingTop: 50,
    paddingRight: 98,
    paddingBottom: 16,
    position: 'absolute',
  },
  amount: {
    color: '#FFF',
    // font-family: Montserrat;
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 19,
  },
  timing: {
    color: '#FFF',
    // font-family: Montserrat,
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 19,
  },
  headerCardContainer: {
    borderTopLeftRadius: 4,
    width: 341,
    height: 104,
    borderTopRightRadius: 4,
  },
});
export default researchStyle;
